/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PlayRouteImport } from './routes/play'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalksIndexRouteImport } from './routes/talks.index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as TalksSlugRouteImport } from './routes/talks.$slug'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as PlayOnlineRouteImport } from './routes/play/online'
import { Route as PlayLocalRouteImport } from './routes/play/local'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiRemyChatRouteImport } from './routes/api.remy-chat'
import { Route as PlayRoomCodeRouteImport } from './routes/play/room.$code'
import { Route as PlayMatchMatchIdRouteImport } from './routes/play/match.$matchId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => PlayRoute,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PlayRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemyChatRoute = ApiRemyChatRouteImport.update({
  id: '/api/remy-chat',
  path: '/api/remy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomCodeRoute = PlayRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMatchMatchIdRoute = PlayMatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => PlayRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule': typeof ScheduleIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/talks': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/local'
    | '/play/online'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/local'
    | '/play/online'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule'
    | '/speakers'
    | '/talks'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/local'
    | '/play/online'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlayRoute: typeof PlayRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiRemyChatRoute: typeof ApiRemyChatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  TalksSlugRoute: typeof TalksSlugRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online': {
      id: '/play/online'
      path: '/online'
      fullPath: '/play/online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/local': {
      id: '/play/local'
      path: '/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof PlayRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remy-chat': {
      id: '/api/remy-chat'
      path: '/api/remy-chat'
      fullPath: '/api/remy-chat'
      preLoaderRoute: typeof ApiRemyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/room/$code': {
      id: '/play/room/$code'
      path: '/room/$code'
      fullPath: '/play/room/$code'
      preLoaderRoute: typeof PlayRoomCodeRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/match/$matchId': {
      id: '/play/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/play/match/$matchId'
      preLoaderRoute: typeof PlayMatchMatchIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayRouteChildren {
  PlayLocalRoute: typeof PlayLocalRoute
  PlayOnlineRoute: typeof PlayOnlineRoute
  PlayMatchMatchIdRoute: typeof PlayMatchMatchIdRoute
  PlayRoomCodeRoute: typeof PlayRoomCodeRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayLocalRoute: PlayLocalRoute,
  PlayOnlineRoute: PlayOnlineRoute,
  PlayMatchMatchIdRoute: PlayMatchMatchIdRoute,
  PlayRoomCodeRoute: PlayRoomCodeRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlayRoute: PlayRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiRemyChatRoute: ApiRemyChatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  TalksSlugRoute: TalksSlugRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
