/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PlayRouteImport } from './routes/play'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayTrainingRouteImport } from './routes/play/training'
import { Route as PlayOnlineRouteImport } from './routes/play/online'
import { Route as PlayLocalRouteImport } from './routes/play/local'
import { Route as PlayAiRouteImport } from './routes/play/ai'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as PlayRoomCodeRouteImport } from './routes/play/room.$code'
import { Route as PlayMatchMatchIdRouteImport } from './routes/play/match.$matchId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTrainingRoute = PlayTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PlayRoute,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => PlayRoute,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PlayRoute,
} as any)
const PlayAiRoute = PlayAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PlayRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomCodeRoute = PlayRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMatchMatchIdRoute = PlayMatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => PlayRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/training': typeof PlayTrainingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/training': typeof PlayTrainingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play': typeof PlayRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/training': typeof PlayTrainingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/match/$matchId': typeof PlayMatchMatchIdRoute
  '/play/room/$code': typeof PlayRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/ai'
    | '/play/local'
    | '/play/online'
    | '/play/training'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/ai'
    | '/play/local'
    | '/play/online'
    | '/play/training'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/play'
    | '/sign-in'
    | '/sign-up'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/posthog'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/play/ai'
    | '/play/local'
    | '/play/online'
    | '/play/training'
    | '/api/auth/$'
    | '/play/match/$matchId'
    | '/play/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlayRoute: typeof PlayRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/training': {
      id: '/play/training'
      path: '/training'
      fullPath: '/play/training'
      preLoaderRoute: typeof PlayTrainingRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/online': {
      id: '/play/online'
      path: '/online'
      fullPath: '/play/online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/local': {
      id: '/play/local'
      path: '/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/ai': {
      id: '/play/ai'
      path: '/ai'
      fullPath: '/play/ai'
      preLoaderRoute: typeof PlayAiRouteImport
      parentRoute: typeof PlayRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/room/$code': {
      id: '/play/room/$code'
      path: '/room/$code'
      fullPath: '/play/room/$code'
      preLoaderRoute: typeof PlayRoomCodeRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/match/$matchId': {
      id: '/play/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/play/match/$matchId'
      preLoaderRoute: typeof PlayMatchMatchIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayRouteChildren {
  PlayAiRoute: typeof PlayAiRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlayOnlineRoute: typeof PlayOnlineRoute
  PlayTrainingRoute: typeof PlayTrainingRoute
  PlayMatchMatchIdRoute: typeof PlayMatchMatchIdRoute
  PlayRoomCodeRoute: typeof PlayRoomCodeRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayAiRoute: PlayAiRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlayOnlineRoute: PlayOnlineRoute,
  PlayTrainingRoute: PlayTrainingRoute,
  PlayMatchMatchIdRoute: PlayMatchMatchIdRoute,
  PlayRoomCodeRoute: PlayRoomCodeRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlayRoute: PlayRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
